const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
const INCREMENT_COUNT = 'INCREMENT_COUNT';
const DECREMENT_COUNT = 'DECREMENT_COUNT';

const actionTypes = {
    TOGGLE_SIDEBAR,
    INCREMENT_COUNT,
    DECREMENT_COUNT
}

export default actionTypes;